import { useState } from "react";
import { StatusBadge } from "../../components/StatusBadge";
import { mockStore } from "../../mocks/mockStore";
import type { Service } from "../../types/models";

export function AdminServices() {
  const [services, setServices] = useState(() => mockStore.services); const [name, setName] = useState(""); const [specialtyId, setSpecialtyId] = useState(""); const [error, setError] = useState("");
  const specialtyName = (id: string) => mockStore.specialties.find((item) => item.id === id)?.name ?? "Chưa xác định";
  function addService() { if (!name.trim() || !specialtyId) return setError("Vui lòng nhập đủ các trường bắt buộc."); const created: Service = { id: `draft-service-${services.length + 1}`, name: name.trim(), specialtyId, durationMinutes: 30, price: 0, currency: "VND", description: "", status: "active", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; setServices((current) => [...current, created]); setName(""); setSpecialtyId(""); setError(""); }
  return <section className="mx-auto max-w-6xl"><p className="text-sm font-medium text-primary">Danh mục dịch vụ</p><h1 className="mt-1 text-2xl font-semibold text-text">Services</h1><form className="mt-5 grid gap-3 rounded-md border border-border bg-surface p-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]" onSubmit={(event) => { event.preventDefault(); addService(); }}><label className="text-sm font-medium text-text">Tên dịch vụ<input className="mt-1 h-10 w-full rounded-md border border-border px-3" onChange={(event) => setName(event.target.value)} value={name} /></label><label className="text-sm font-medium text-text">Chuyên khoa<select className="mt-1 h-10 w-full rounded-md border border-border bg-surface px-3" onChange={(event) => setSpecialtyId(event.target.value)} value={specialtyId}><option value="">Chọn chuyên khoa</option>{mockStore.specialties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="h-10 self-end rounded-md bg-primary px-3 text-sm font-semibold text-white" type="submit">Thêm dịch vụ</button>{error ? <p className="text-sm text-danger sm:col-span-3" role="alert">{error}</p> : null}</form><div className="mt-6 overflow-x-auto rounded-md border border-border bg-surface"><table aria-label="Services" className="hidden min-w-full text-left text-sm md:table"><thead className="bg-surface-muted text-text-muted"><tr><th className="p-3">Dịch vụ</th><th className="p-3">Chuyên khoa</th><th className="p-3">Thời lượng</th><th className="p-3">Trạng thái</th></tr></thead><tbody>{services.map((service) => <tr className="border-t border-border" key={service.id}><td className="p-3 font-medium text-text">{service.name}</td><td className="p-3">{specialtyName(service.specialtyId)}</td><td className="p-3">{service.durationMinutes} phút</td><td className="p-3"><StatusBadge status={service.status} /></td></tr>)}</tbody></table><ul className="divide-y divide-border md:hidden">{services.map((service) => <li className="p-3" key={service.id}><p className="font-medium text-text">{service.name}</p><p className="mt-1 text-sm text-text-muted">{specialtyName(service.specialtyId)} · {service.durationMinutes} phút</p><div className="mt-2"><StatusBadge status={service.status} /></div></li>)}</ul></div></section>;
}
