import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { StatusBadge } from "../../components/StatusBadge";
import type { Specialty } from "../../types/models";
import { catalogQueryOptions } from "../catalog/catalogService";

export function AdminSpecialties() {
  const { data: specialtyResponse } = useQuery(catalogQueryOptions.allSpecialties());
  const [draftSpecialties, setDraftSpecialties] = useState<Specialty[]>([]); const [name, setName] = useState(""); const [error, setError] = useState("");
  const specialties = [...(specialtyResponse?.data ?? []), ...draftSpecialties];
  function addSpecialty() { if (!name.trim()) return setError("Vui lòng nhập tên chuyên khoa."); const created: Specialty = { id: `draft-specialty-${specialties.length + 1}`, name: name.trim(), description: "", status: "active", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; setDraftSpecialties((current) => [...current, created]); setName(""); setError(""); }
  return <section className="mx-auto max-w-6xl"><p className="text-sm font-medium text-primary">Danh mục chuyên môn</p><h1 className="mt-1 text-2xl font-semibold text-text">Specialties</h1><form className="mt-5 flex flex-wrap items-end gap-3 rounded-md border border-border bg-surface p-4" onSubmit={(event) => { event.preventDefault(); addSpecialty(); }}><label className="min-w-0 flex-1 text-sm font-medium text-text">Tên chuyên khoa<input className="mt-1 h-10 w-full rounded-md border border-border px-3" onChange={(event) => setName(event.target.value)} value={name} /></label><button className="h-10 rounded-md bg-primary px-3 text-sm font-semibold text-white" type="submit">Thêm chuyên khoa</button>{error ? <p className="w-full text-sm text-danger" role="alert">{error}</p> : null}</form><div className="mt-6 overflow-x-auto rounded-md border border-border bg-surface"><table aria-label="Specialties" className="hidden min-w-full text-left text-sm md:table"><thead className="bg-surface-muted text-text-muted"><tr><th className="p-3">Chuyên khoa</th><th className="p-3">Mô tả</th><th className="p-3">Trạng thái</th></tr></thead><tbody>{specialties.map((specialty) => <tr className="border-t border-border" key={specialty.id}><td className="p-3 font-medium text-text">{specialty.name}</td><td className="p-3 text-text-muted">{specialty.description || "Chưa có mô tả"}</td><td className="p-3"><StatusBadge status={specialty.status} /></td></tr>)}</tbody></table><ul className="divide-y divide-border md:hidden">{specialties.map((specialty) => <li className="p-3" key={specialty.id}><p className="font-medium text-text">{specialty.name}</p><p className="mt-1 text-sm text-text-muted">{specialty.description || "Chưa có mô tả"}</p><div className="mt-2"><StatusBadge status={specialty.status} /></div></li>)}</ul></div></section>;
}
