import { useState } from "react";
import { StatusBadge } from "../../components/StatusBadge";
import { mockStore } from "../../mocks/mockStore";
import type { Staff, UserRole } from "../../types/models";

const staffRoles: Array<Extract<UserRole, "receptionist" | "nurse" | "admin">> = ["receptionist", "nurse", "admin"];
export function AdminStaff() {
  const [staff, setStaff] = useState(() => mockStore.staff); const [name, setName] = useState(""); const [role, setRole] = useState<Staff["role"]>("receptionist"); const [error, setError] = useState("");
  function addStaff() { if (!name.trim()) return setError("Vui lòng nhập tên nhân sự."); const created: Staff = { id: `draft-staff-${staff.length + 1}`, userId: `draft-user-${staff.length + 1}`, fullName: name.trim(), phone: "", email: "", role, status: "active", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; setStaff((current) => [...current, created]); setName(""); setError(""); }
  return <section className="mx-auto max-w-6xl"><p className="text-sm font-medium text-primary">Quản trị nhân sự</p><h1 className="mt-1 text-2xl font-semibold text-text">Staff</h1><form className="mt-5 grid gap-3 rounded-md border border-border bg-surface p-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]" onSubmit={(event) => { event.preventDefault(); addStaff(); }}><label className="text-sm font-medium text-text">Tên nhân sự<input className="mt-1 h-10 w-full rounded-md border border-border px-3" onChange={(event) => setName(event.target.value)} value={name} /></label><label className="text-sm font-medium text-text">Vai trò<select className="mt-1 h-10 w-full rounded-md border border-border bg-surface px-3" onChange={(event) => setRole(event.target.value as Staff["role"])} value={role}>{staffRoles.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><button className="h-10 self-end rounded-md bg-primary px-3 text-sm font-semibold text-white" type="submit">Thêm nhân sự</button>{error ? <p className="text-sm text-danger sm:col-span-3" role="alert">{error}</p> : null}</form><div className="mt-6 overflow-x-auto rounded-md border border-border bg-surface"><table aria-label="Staff" className="hidden min-w-full text-left text-sm md:table"><thead className="bg-surface-muted text-text-muted"><tr><th className="p-3">Nhân sự</th><th className="p-3">Vai trò</th><th className="p-3">Email</th><th className="p-3">Trạng thái</th></tr></thead><tbody>{staff.map((item) => <tr className="border-t border-border" key={item.id}><td className="p-3 font-medium text-text">{item.fullName}</td><td className="p-3">{item.role}</td><td className="p-3">{item.email || "Chưa cập nhật"}</td><td className="p-3"><StatusBadge status={item.status} /></td></tr>)}</tbody></table><ul className="divide-y divide-border md:hidden">{staff.map((item) => <li className="p-3" key={item.id}><p className="font-medium text-text">{item.fullName}</p><p className="mt-1 text-sm text-text-muted">{item.role} · {item.email || "Chưa cập nhật"}</p><div className="mt-2"><StatusBadge status={item.status} /></div></li>)}</ul></div></section>;
}
